// 环境变量列表仅在此维护！
const globalAPIParamsList = [
  'BASE_URL',
  'PROD_PREFIX',
  'TITLE_CENTRE_CONFIG',
  'BASE_URL_WARNING',
  'HONGLING_BASE_URL',
  'API_PREFIX_CENTRE_CONFIG',
  'FILE_VIEW',
  'FILE_SERVER',
  'MAP_CONFIG_MONITOR_WARNING_ONEPIC',
  'SWAN_TENANT_ID_MONITOR_WARNING_ONEPIC',
  'SWAN_SYSTEM_ID_MONITOR_WARNING_ONEPIC',
  'ONEPIC_BASE_URL',
  'PORTAL_URL',
  'DEPLOY_TYPE_CENTRE_CONFIG',
  'API_PREFIX_USER_CENTER',
  'CLIENT_ID_CENTRE_CONFIG',
  'CALLBACK_URL_CENTRE_CONFIG',
  'MAP_TYPE',
  'ONE_MONITORING_LINK',
  'ONE_WARNING_LINK',
  'TIANDITU_TOKEN',
  'CHANGZHOU_API_PREFIX',
  'CHANGZHOU_APP_ID',
  'CHANGZHOU_APP_SECRET',
  'IS_CHANGZHOU_PROJECT',
  'LAYOUT_MENU',
  'SUB_HEADER',
  'LAYOUT_HEADER',
  'STRATEGY_AFTER_CONFIG'
];

module.exports = { globalAPIParamsList };
